import openapiTS, { astToString } from 'openapi-typescript'
import { mkdir } from 'node:fs/promises'

const specUrl = new URL('../openapi/agentos-v3.json', import.meta.url)
const outDir = new URL('../src/generated/', import.meta.url)
await mkdir(outDir, { recursive: true })

// 2. Manifesto (spec carregado uma vez, reaproveitado pelos tipos abaixo)
type Spec = {
  paths: Record<string, Record<string, any>>
  components: { schemas: Record<string, any> }
}
const spec = (await Bun.file(specUrl).json()) as Spec

// 1. Tipos
// Deviation from brief: the real spec has a duplicate operationId `get_config`
// (GET /config and GET /components/{component_id}/configs/{version}), which
// openapi-typescript v7 rejects via its built-in redocly lint
// ("Every operation must have a unique `operationId`"). This has no effect on
// `paths` (keyed by method+path) or on the routes manifest below (keyed by
// method+path from the raw JSON), so it's safe to resolve by deduplicating the
// operationId on a deep-cloned copy of the spec before feeding it to
// openapiTS, rather than passing the spec URL directly as the brief's snippet
// does. See task-2-report.md for details.
const specForTypes = structuredClone(spec) as unknown as Record<string, any>
specForTypes.paths['/components/{component_id}/configs/{version}'].get.operationId = 'get_component_config_version'
const ast = await openapiTS(specForTypes as any, { alphabetize: true })
const header = '// Generated by scripts/generate.ts from openapi/agentos-v3.json. Do not edit.\n'
await Bun.write(new URL('openapi.d.ts', outDir), header + astToString(ast))
const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const
const KNOWN_CT = ['application/json', 'multipart/form-data', 'application/x-www-form-urlencoded']

const lines: string[] = []
const problems: string[] = []
for (const path of Object.keys(spec.paths).sort()) {
  for (const method of METHODS) {
    const op = spec.paths[path]![method]
    if (!op) continue
    const query: string[] = (op.parameters ?? []).filter((p: any) => p.in === 'query').map((p: any) => p.name)
    const content = op.requestBody?.content ?? {}
    const contentType = Object.keys(content)[0] ?? null
    if (contentType && !KNOWN_CT.includes(contentType)) problems.push(`${method} ${path}: unknown content type ${contentType}`)
    let schema = contentType ? content[contentType].schema ?? {} : {}
    if (schema.$ref) schema = spec.components.schemas[schema.$ref.split('/').pop()] ?? {}
    const bodyKeys: string[] = Object.keys(schema.properties ?? {})
    const clash = query.filter((q) => bodyKeys.includes(q))
    if (clash.length) problems.push(`${method} ${path}: query/body collision on ${clash.join(', ')}`)
    const q = query.map((k) => `'${k}'`).join(', ')
    lines.push(`  '${method} ${path}': { query: [${q}], contentType: ${contentType ? `'${contentType}'` : 'null'} },`)
  }
}
if (problems.length) {
  console.error(problems.join('\n'))
  process.exit(1)
}

const manifest = `${header}
export type ContentType = 'application/json' | 'multipart/form-data' | 'application/x-www-form-urlencoded'

export interface RouteMeta {
  readonly query: readonly string[]
  readonly contentType: ContentType | null
}

export const routes = {
${lines.join('\n')}
} as const satisfies Record<string, RouteMeta>

export type RouteKey = keyof typeof routes
`
await Bun.write(new URL('routes.gen.ts', outDir), manifest)
console.log(`generated ${lines.length} routes`)
